CREATE DATABASE TICKETMASTER;

USE TICKETMASTER;

CREATE TABLE [CUSTOMER](
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[EMAIL] VARCHAR(80) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[CPF] VARCHAR(11),
	
	CONSTRAINT PK_CUSTOMER PRIMARY KEY ([ID])
);

CREATE TABLE [PRODUCER](
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[EMAIL] VARCHAR(80) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[CPF] VARCHAR(11),

	CONSTRAINT PK_PRODUCER PRIMARY KEY ([ID])	
);

CREATE TABLE [EVENT](
    [ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[FEDERATIVEUNIT] INT NOT NULL,
	[DATE] DATETIME NOT NULL,
	[PRODUCERID] INT,
	[TOTALAMOUNT] INT,
	[CURRENTQUANTITYTICKETS] INT,
	[DESCRIPTION] VARCHAR(150),
	
	CONSTRAINT PK_EVENT PRIMARY KEY ([ID]),
	CONSTRAINT FK_PRODUCERID_EVENT FOREIGN KEY(PRODUCERID) REFERENCES [PRODUCER]([ID])
);

CREATE TABLE [TICKET](
	[ID] INT NOT NULL IDENTITY(1,1),
	[CUSTOMERID] INT NOT NULL,
	[EVENTID] INT NOT NULL,
	[FLAGCONSUMED] BIT,
	
	CONSTRAINT PK_TICKET PRIMARY KEY ([ID]),
	CONSTRAINT FK_CUSTOMERID_TICKET FOREIGN KEY([CUSTOMERID]) REFERENCES [CUSTOMER]([ID]),
	CONSTRAINT FK_IDEVENTID_TICKET FOREIGN KEY([EVENTID]) REFERENCES [EVENT]([ID])
);